// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: wal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WALRecord_Type int32

const (
	WALRecord_TRACE  WALRecord_Type = 0
	WALRecord_METRIC WALRecord_Type = 1
	WALRecord_LOG    WALRecord_Type = 2
)

// Enum value maps for WALRecord_Type.
var (
	WALRecord_Type_name = map[int32]string{
		0: "TRACE",
		1: "METRIC",
		2: "LOG",
	}
	WALRecord_Type_value = map[string]int32{
		"TRACE":  0,
		"METRIC": 1,
		"LOG":    2,
	}
)

func (x WALRecord_Type) Enum() *WALRecord_Type {
	p := new(WALRecord_Type)
	*p = x
	return p
}

func (x WALRecord_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALRecord_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_proto_enumTypes[0].Descriptor()
}

func (WALRecord_Type) Type() protoreflect.EnumType {
	return &file_wal_proto_enumTypes[0]
}

func (x WALRecord_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALRecord_Type.Descriptor instead.
func (WALRecord_Type) EnumDescriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{0, 0}
}

type WALRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WALRecord_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=wal.WALRecord_Type" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // Serialized pdata
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALRecord) Reset() {
	*x = WALRecord{}
	mi := &file_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALRecord) ProtoMessage() {}

func (x *WALRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALRecord.ProtoReflect.Descriptor instead.
func (*WALRecord) Descriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WALRecord) GetType() WALRecord_Type {
	if x != nil {
		return x.Type
	}
	return WALRecord_TRACE
}

func (x *WALRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WALRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_wal_proto protoreflect.FileDescriptor

const file_wal_proto_rawDesc = "" +
	"\n" +
	"\twal.proto\x12\x03wal\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\tWALRecord\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.wal.WALRecord.TypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"&\n" +
	"\x04Type\x12\t\n" +
	"\x05TRACE\x10\x00\x12\n" +
	"\n" +
	"\x06METRIC\x10\x01\x12\a\n" +
	"\x03LOG\x10\x02B#Z!OTEL_Tail_Sampler/internal/wal/pbb\x06proto3"

var (
	file_wal_proto_rawDescOnce sync.Once
	file_wal_proto_rawDescData []byte
)

func file_wal_proto_rawDescGZIP() []byte {
	file_wal_proto_rawDescOnce.Do(func() {
		file_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)))
	})
	return file_wal_proto_rawDescData
}

var file_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wal_proto_goTypes = []any{
	(WALRecord_Type)(0),           // 0: wal.WALRecord.Type
	(*WALRecord)(nil),             // 1: wal.WALRecord
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_wal_proto_depIdxs = []int32{
	0, // 0: wal.WALRecord.type:type_name -> wal.WALRecord.Type
	2, // 1: wal.WALRecord.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_wal_proto_init() }
func file_wal_proto_init() {
	if File_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_depIdxs,
		EnumInfos:         file_wal_proto_enumTypes,
		MessageInfos:      file_wal_proto_msgTypes,
	}.Build()
	File_wal_proto = out.File
	file_wal_proto_goTypes = nil
	file_wal_proto_depIdxs = nil
}
