// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SamplingDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DecidedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	DecidedBy     string                 `protobuf:"bytes,4,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	EventStart    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=event_start,json=eventStart,proto3" json:"event_start,omitempty"`
	EventEnd      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=event_end,json=eventEnd,proto3" json:"event_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingDecision) Reset() {
	*x = SamplingDecision{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingDecision) ProtoMessage() {}

func (x *SamplingDecision) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingDecision.ProtoReflect.Descriptor instead.
func (*SamplingDecision) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *SamplingDecision) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SamplingDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SamplingDecision) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *SamplingDecision) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

func (x *SamplingDecision) GetEventStart() *timestamppb.Timestamp {
	if x != nil {
		return x.EventStart
	}
	return nil
}

func (x *SamplingDecision) GetEventEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.EventEnd
	}
	return nil
}

type TriggerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEvent) Reset() {
	*x = TriggerEvent{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEvent) ProtoMessage() {}

func (x *TriggerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEvent.ProtoReflect.Descriptor instead.
func (*TriggerEvent) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TriggerEvent) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *TriggerEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type GossipMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GossipMessage_SamplingDecision
	//	*GossipMessage_TriggerEvent
	Payload       isGossipMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *GossipMessage) GetPayload() isGossipMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GossipMessage) GetSamplingDecision() *SamplingDecision {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_SamplingDecision); ok {
			return x.SamplingDecision
		}
	}
	return nil
}

func (x *GossipMessage) GetTriggerEvent() *TriggerEvent {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_TriggerEvent); ok {
			return x.TriggerEvent
		}
	}
	return nil
}

type isGossipMessage_Payload interface {
	isGossipMessage_Payload()
}

type GossipMessage_SamplingDecision struct {
	SamplingDecision *SamplingDecision `protobuf:"bytes,1,opt,name=sampling_decision,json=samplingDecision,proto3,oneof"`
}

type GossipMessage_TriggerEvent struct {
	TriggerEvent *TriggerEvent `protobuf:"bytes,2,opt,name=trigger_event,json=triggerEvent,proto3,oneof"`
}

func (*GossipMessage_SamplingDecision) isGossipMessage_Payload() {}

func (*GossipMessage_TriggerEvent) isGossipMessage_Payload() {}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x06gossip\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\x10SamplingDecision\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"decided_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x04 \x01(\tR\tdecidedBy\x12;\n" +
	"\vevent_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"eventStart\x127\n" +
	"\tevent_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\beventEnd\"\x91\x01\n" +
	"\fTriggerEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xa0\x01\n" +
	"\rGossipMessage\x12G\n" +
	"\x11sampling_decision\x18\x01 \x01(\v2\x18.gossip.SamplingDecisionH\x00R\x10samplingDecision\x12;\n" +
	"\rtrigger_event\x18\x02 \x01(\v2\x14.gossip.TriggerEventH\x00R\ftriggerEventB\t\n" +
	"\apayloadB&Z$OTEL_Tail_Sampler/internal/gossip/pbb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gossip_proto_goTypes = []any{
	(*SamplingDecision)(nil),      // 0: gossip.SamplingDecision
	(*TriggerEvent)(nil),          // 1: gossip.TriggerEvent
	(*GossipMessage)(nil),         // 2: gossip.GossipMessage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_gossip_proto_depIdxs = []int32{
	3, // 0: gossip.SamplingDecision.decided_at:type_name -> google.protobuf.Timestamp
	3, // 1: gossip.SamplingDecision.event_start:type_name -> google.protobuf.Timestamp
	3, // 2: gossip.SamplingDecision.event_end:type_name -> google.protobuf.Timestamp
	3, // 3: gossip.TriggerEvent.started_at:type_name -> google.protobuf.Timestamp
	0, // 4: gossip.GossipMessage.sampling_decision:type_name -> gossip.SamplingDecision
	1, // 5: gossip.GossipMessage.trigger_event:type_name -> gossip.TriggerEvent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	file_gossip_proto_msgTypes[2].OneofWrappers = []any{
		(*GossipMessage_SamplingDecision)(nil),
		(*GossipMessage_TriggerEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
